//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SysPortal.rc
//
#define IDS_PROJNAME                    100
#define IDR_SysPortal                   100
#define IDD_DIALOGPROP                  101
#define IDR_DISPRES                     102
#define IDR_RBUTTON                     102
#define IDI_DISPRES                     103
#define IDI_HOTINTERNET                 103
#define IDD_DISPRES                     104
#define IDD_ABOUT                       104
#define IDD_PANELMENUPROP               105
#define IDD_PANELINTERNETOPTIONS        106
#define IDD_CPANELUSERCONFIG            107
#define IDD_TREEEDITOR                  108
#define IDD_EXIT                        109
#define IDB_CHECK                       110
#define IDR_LBUTTON                     112
#define IDD_PROPERTIES                  113
#define IDI_WORD_BOOK                   114
#define IDD_TOOLTIPS                    115
#define IDB_BITMAPLOGO                  118
#define IDB_ITEMDEFAULT                 120
#define IDB_ITEMMASK                    121
#define IDB_EXPLORER                    123
#define IDB_NETSCAPE                    124
#define IDB_MERC                        125
#define IDI_ICON2                       126
#define IDB_LOCALMENU                   127
#define IDB_INTRANET                    128
#define IDB_FIND                        129
#define IDB_MIS                         130
#define IDB_BITMAP1                     131
#define IDB_BITMAP_TITLE                132
#define IDB_BITMAP2                     133
#define IDI_FOLDER                      134
#define IDB_ITEMDEFAULT_N               135
#define IDB_ISRAEL                      136
#define IDB_USA                         137
#define IDB_HANDICO                     138
#define IDB_ABOUT                       139
#define IDB_CONFIG                      144
#define IDB_CLOSE                       146
#define IDB_WORKGROUPS                  147
#define IDB_PERSONAL                    148
#define IDB_COMMENT                     149
#define IDB_BOOKS                       150
#define IDB_PUBLIC_LINK                 151
#define IDB_PUBLIC_LINK_DIALOG          152
#define IDB_WORKGROUPS_DIALOG           153
#define IDB_FIND_DLG                    154
#define IDI_INTERNET_OPTIONS            156
#define IDI_MENU_OPTIONS                157
#define IDI_USER_OPTIONS                160
#define IDB_SELECTED                    161
#define IDB_SELECTING                   163
#define IDB_MENU_SAMPLES                164
#define IDB_LIVEUPDATE                  166
#define IDB_NEXT                        167
#define IDB_NEXT_S                      168
#define IDB_NETSCAPE_MIN                171
#define IDB_EXPLORER_MIN                172
#define IDB_DEFAULT_BROWSER             173
#define IDB_INTERNET_ACCELERATE         174
#define IDB_ISDN_FIX                    175
#define IDB_USER                        176
#define IDI_ICON_LINK                   177
#define IDI_ICON_CLOSE                  179
#define IDI_ICON_OPEN                   180
#define IDI_ICON_PERSONAL_LINK          181
#define IDB_MINUS                       182
#define IDB_PLUS                        183
#define IDB_EDIT_PERSONAL_LINE          184
#define IDB_DATABASE                    185
#define IDR_MENU_POPUP_TREE             186
#define IDC_CURSOR_NO_DROP_1            191
#define IDC_USER_NAME                   1000
#define IDC_WORD_BOX                    1001
#define IDC_CHECK_AUTOSTART             1004
#define IDC_HOST_NAME                   1006
#define IDC_BUTTONGO                    1007
#define IDC_MESSAGE                     1008
#define IDC_COMBO1                      1009
#define IDC_COMBO_UPDATE                1009
#define IDC_COMBO2                      1010
#define IDC_CHECKISDN                   1011
#define IDC_BUTTON_SHARED_BOOKMARK      1012
#define IDC_BUTTON_STORAGE_SERVER       1013
#define IDC_ACCELERATE                  1014
#define IDC_DOMAIN                      1015
#define IDC_BUTTON3                     1016
#define IDC_BUTTON4                     1017
#define IDC_SYSTEM_MENU                 1026
#define IDC_BUTTON1                     1027
#define IDC_EDIT_WORKGROUP              1027
#define IDC_BUTTON_CANCEL               1027
#define IDC_EDIT_FIND_SYSTEM            1028
#define IDC_TAB_MAIN                    1029
#define IDC_TITLE_NAME                  1031
#define IDC_EDIT1                       1032
#define IDC_EDIT_PERSONAL_LINE          1032
#define IDC_EDIT_COMPUTER_NAME          1032
#define IDC_EDIT2                       1033
#define IDC_EDIT_VIRTUAL_LIBRARY        1033
#define IDC_EDIT_HOST_NAME              1033
#define IDC_EDIT_GROUP_FOLDER           1034
#define IDC_BUTTON_IMMEDIATELY          1035
#define IDC_RADIO_INTERNET_EXPLORER     1036
#define IDC_RADIO_NETSCAPE              1037
#define IDC_RADIO_SYSTEM_DEFAULT_BROWSER 1038
#define IDC_RADIO_NEW_WINDOW            1039
#define IDC_RADIO_ACTIVE_WINDOW         1040
#define IDC_CHECK_RANDOM                1041
#define IDC_EDIT_DESCRIPTION            1043
#define IDC_TREE_CTRL                   1044
#define IDM_DISPRES                     1050
#define ID_EXIT                         40007
#define ID_ABOUT                        40008
#define ID_PROPERTIES                   40009
#define ID_POPMENUTREE_EXPANDALL        40012
#define ID_POPMENUTREE_COLLAPSED        40013
#define ID_POPMENUTREE_DELETE           40014
#define ID_POPMENUTREE_INSERTFOLDER     40015
#define ID_POPMENUTREE_INSERTITEM       40016
#define ID_POPMENUTREE_INSERTCOPY       40017

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        194
#define _APS_NEXT_COMMAND_VALUE         40018
#define _APS_NEXT_CONTROL_VALUE         1046
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
