// SysPortal.idl : IDL source for SysPortal.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (SysPortal.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(4914A081-DA4A-11D3-9F4B-005004816FFF),
	version(1.0),
	helpstring("SysPortal 1.0 Type Library")
]
library SYSPORTALLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

};
